safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:    /
url: http://localhost:4000

source:      .
destination: ./_site
plugins:     ./_plugins
exclude:     Rakefile, Gemfile, Gemfile.lock, README.md, .gitignore

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date
